app/forms/searchForm.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, IntegerField 
from wtforms.fields import DateField

class AdvancedSearch(FlaskForm):
    manufacturingDateFilter = DateField(
        render_kw={"placeholder": "Manufacuring date"})
    priceFilter = IntegerField(
        render_kw={"placeholder": "Price"})
    submit = SubmitField("Advanced Search")

app/routes/auth_routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import current_user, login_user, logout_user, login_required
from app.models.userModel import UserModel
from app import db 
from app.models.productModel import Cart
from app.forms import regLoginForm
from flask_bcrypt import Bcrypt
from datetime import datetime
from utils.cartUtils import cart_init

auth_bp = Blueprint('auth', __name__)

bcrypt = Bcrypt()

@auth_bp.route("/", methods=['POST', 'GET'])
@auth_bp.route("/<error>", methods=['POST', 'GET'])
def main_view(error=""):
    login_form = regLoginForm.LoginForm()
    register_form = regLoginForm.RegisterForm()

    def validate_username(self, username):
        if UserModel.query.filter_by(username=username.data).first():
            raise ValidationError("This username already exists. Please choose something unique")

    register_form.validate_username = validate_username

    if request.method == 'POST':
        if request.form.get('loginAction') == 'Login':
            return render_template("mainView.html", form=login_form)
        else:
            return render_template("mainView.html", form=register_form)
    return render_template("mainView.html", form=login_form, error=error)

@auth_bp.route("/login.html", methods=['GET', 'POST'])
def login():
    login_form = regLoginForm.LoginForm()
    if login_form.validate_on_submit():
        user = UserModel.query.filter_by(username=login_form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, login_form.password.data):
            login_user(user)
            cart_init(db, current_user)
            return redirect(url_for('dashboard.dashboard'))
    error = "Invalid Username or Password"
    return redirect(url_for('auth.main_view', error=error))

@auth_bp.route("/register.html", methods=['GET', 'POST'])
def register():
    registerForm = regLoginForm.RegisterForm()
    if registerForm.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            registerForm.password.data)
        checkUsername = UserModel.query.filter_by(
            username=registerForm.username.data).first()
        if (checkUsername):
            return redirect(url_for('auth.main_view', error="Username already taken"))
        new_user = UserModel(username=registerForm.username.data,
                             password=hashed_password, firstOrder=True)
        print('Creating a new cart.')
        db.session.add(new_user)
        db.session.commit()
        new_cart = Cart(userId=new_user.uuid, totalValue=0, products={})
        db.session.add(new_cart)
        db.session.commit()
        login_user(new_user)
        return redirect(url_for('dashboard.dashboard')) 

@auth_bp.route("/logout", methods=['POST', 'GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.main_view'))

app/routes/cart_routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user
from app.models.productModel import Cart, ProductModel
from app import  db
from utils.cartUtils import updateCart
import razorpay
import os

cart_bp = Blueprint('cart', __name__)

@cart_bp.route('/editCart/<kwargs>', methods=['POST'])
@login_required
def edit_cart(kwargs):
    kwargs = eval(kwargs)

    productId = kwargs['productId']
    productToAdd = ProductModel.query.filter_by(productId=productId).first()
    cart = Cart.query.filter_by(userId=current_user.uuid).first()
    productKey = str(productToAdd.productId)
    if 'action' in kwargs.keys():
        action = kwargs['action']
    else:
        action = "add"
    if productKey not in cart.products:
        cart.products[productKey] = 0

    match action:
        case "remove":
            cart.products[productKey] -= 1
            productToAdd.quantityInCart -= 1
            cart.totalValue -= productToAdd.valuePerUnit
        case "add":
            cart.products[productKey] += 1
            productToAdd.quantityInCart += 1
            productToAdd.quantityInStore -= 1
            cart.totalValue += productToAdd.valuePerUnit
        case "clean":
            quantity = cart.products[productKey]
            value = productToAdd.valuePerUnit
            cart.totalValue -= (quantity*value)
            productToAdd.quantityInCart = 0
            cart.products[productKey] = 0
    db.session.commit()
    if 'origin' in kwargs.keys():
        if (kwargs['origin'] == 'cart'):
            return redirect(url_for('cart.cart_view'))
        elif (kwargs['origin'] == 'detailView'):
            return redirect(url_for('product.product_detail_view', productId=kwargs['productId']))
    return redirect(url_for('dashboard.dashboard'))

@cart_bp.route("/cart.html", methods=['POST', 'GET'])
@cart_bp.route('/cart/<message>', methods=['POST', 'GET'])
@login_required
def cart_view(message=None):
    cart = Cart.query.filter_by(userId=current_user.uuid).first()
    total = cart.totalValue
    discount = 0
    if (cart):
        cartData = cart.products
        cartDataProp = {}
        for product in cartData:
            productData = ProductModel.query.filter_by(
                productId=int(product)).first()
            cartDataProp[productData] = cartData[product]
        cartDataProp = {x: y for x, y in cartDataProp.items() if y != 0}
        if current_user.firstOrder:
            discount = 15*total/100
            discountMessage = 'First order discount'
            return render_template('cart.html', cartDataProp=cartDataProp, totalValue=total, message=message, discount=discount, discountMessage=discountMessage)
        return render_template('cart.html', cartDataProp=cartDataProp, totalValue=total, message=message, discount=discount)
    return redirect(url_for('dashboard'))


@cart_bp.route("/handleBuyNow.html", methods=['POST'])
async def handleBuyNow():
    KEY_ID = os.getenv("KEY_ID")
    KEY_SECRET = os.getenv("KEY_SECRET")
    client = razorpay.Client(auth=(KEY_ID, KEY_SECRET))
    client.set_app_details({"title" : "flask", "version" : "1.0.0"})
    print(client)
    existingCart = Cart.query.filter_by(userId=current_user.uuid).first()
    changed = updateCart(db, existingCart)
    if changed:
        return redirect(url_for('cart.cart_view', message='Some items in the cart has been updated. Please view the cart.'))
    for product in existingCart.products.keys():
        productToUpdate = ProductModel.query.filter_by(
            productId=int(product)).first()

    order = client.order.create({
        "amount": existingCart.totalValue*100,
        "currency": "INR",
        
    })
    print('_______________________')
    print(order)
    print(client.order.all())
    print('_______________________')

    return render_template('payment.html',order=order,KEY_ID=KEY_ID)

    # Cart.query.filter_by(userId=current_user.uuid).delete()
    # newCart = Cart(userId=current_user.uuid, totalValue=0, products={})
    # current_user.firstOrder = False
    # db.session.add(newCart)
    # db.session.commit()
    # return redirect(url_for('dashboard.dashboard', message="Thank you for your purchase !!"))

app/routes/product_routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user
from app.models.productModel import ProductModel
from app import db
from app.forms import Product as productForm
from datetime import datetime

product_bp = Blueprint('product', __name__)

@product_bp.route("/addProduct.html", methods=['GET', 'POST'])
def add_product():
    form = productForm.ProductForm()
    if form.validate_on_submit():
        new_product = ProductModel(
            productName=form.productName.data,
            productImage='/static/' + form.productImage.data,
            manufacturingDate=form.manufacturingDate.data,
            expiryDate=form.expiryDate.data,
            quantityInStore=form.quantityInStore.data,
            section=request.form['section'].lower(),
            valuePerUnit=form.valuePerUnit.data,
            addedOnDate=datetime.now()
        )
        db.session.add(new_product)
        db.session.commit()
        return redirect(url_for('auth.admin', message="Added " + new_product.productName))
    return render_template("addProduct.html", form=form)

@product_bp.route('/productDetailView/<productId>', methods=['POST', 'GET'])
@login_required
def product_detail_view(productId):
    product_data = ProductModel.query.filter_by(productId=productId).first()
    return render_template('productDetailView.html', productData=product_data)


@product_bp.route("/editProduct.html", methods=['POST'])
def edit_product():
    productToEdit = request.form['productToEdit']
    productInStock = request.form['productInStock']
    productEditForm = addProductForm.EditProductForm()
    product = ProductModel.query.filter_by(productName=productToEdit).first()
    try:
        productChangeStock = request.form['changeStock']
    except:
        productChangeStock = False
    if product:
        if productChangeStock == 'changeStock':
            if productInStock == "Out of stock":
                editEngagement(db, product, -5)
                product.quantityInStore = 0
            elif productInStock == "Change stock":
                editEngagement(db, product, +1)
                print("Updating product." + product.productName)
                product.quantityInStore = productEditForm.unitsInStock.data
                product.addedOnDate = datetime.now()
        if productEditForm.productValue.data:
            editEngagement(db, product, +1)
            product.valuePerUnit = productEditForm.productValue.data
        db.session.commit()
        return redirect(url_for('admin', message="Updated "+product.productName))
    else:
        return redirect(url_for('admin', message="Couldn't find the product"))

app/routes/ticket_routes.py
from flask import Blueprint, redirect, url_for
from flask_login import login_required, current_user
from app.models.ticketModel import TicketModel
from app.models.userModel import UserModel
from app import  db

ticket_bp = Blueprint('ticket', __name__)

@ticket_bp.route("/requestManager.html", methods=['GET', 'POST'])
def request_manager():
    new_ticket = TicketModel(
        ticketRequest='Access',
        ticketTarget='ManagerAccess',
        ticketDetails=f"Please provide access to new user {current_user.username}",
        ticketRaisedBy=current_user.uuid
    )
    db.session.add(new_ticket)
    db.session.commit()
    return redirect(url_for('dashboard.dashboard', message="Successfully raised a ticket!"))

@ticket_bp.route("/raiseTicket.html", methods=['POST'])
def raise_ticket():
    form = regLoginForm.TicketForm()
    if form.validate_on_submit():
        new_ticket = TicketModel(
            ticketRequest=form.ticketRequest.data,
            ticketTarget=form.ticketTarget.data,
            ticketDetails=form.ticketDetails.data,
            ticketRaisedBy=current_user.uuid
        )
        db.session.add(new_ticket)
        db.session.commit()
        return redirect(url_for('auth.admin', message="Successfully raised a ticket!"))

@ticket_bp.route("/handleTicket.html/<kwargs>", methods=['POST'])
def handle_ticket(kwargs):
    kwargs = eval(kwargs)
    ticket_id, approved = kwargs['ticketId'], kwargs['approved']
    ticket_details = TicketModel.query.filter_by(ticketId=ticket_id).first()
    if approved:
        ticket_details.action = 'Approved'
        if ticket_details.ticketRequest == 'Access':
            user_to_promote = UserModel.query.filter_by(uuid=ticket_details.ticketRaisedBy).first()
            if ticket_details.ticketTarget == "ManagerAccess":
                user_to_promote.isManager = True
            else:
                user_to_promote.isAdmin = True
    else:
        ticket_details.action = 'Denied'
    db.session.commit()
    return redirect(url_for('auth.admin', message='Ticket closed!'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
    />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GroceryHub</title>
  </head>
  <nav
    class="navbar navbar-expand-lg navbar-light bg-light"
    style="background-color: #dee2e6 !important"
  >
    <div style="margin: 0 10rem 0 10rem; display: flex; flex-direction: row">
      <a class="navbar-brand" href="{{url_for('dashboard.dashboard')}}"
        >GroceryHub</a
      >
      {% if current_user.is_authenticated %}
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('dashboard.dashboard')}}"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('cart.cart_view')}}"> Cart</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('section.section_view')}}"
              >Sections</a
            >
          </li>
          {% if current_user.isAdmin %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.admin')}}">Admin </a>
          </li>
          {% elif current_user.isManager %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.admin')}}">Manager </a>
          </li>
          {% endif %}
          <form
            class="form-inline my-2 my-lg-0"
            method="POST"
            action="{{url_for('section.search')}}"
          >
            <input
              class="form-control mr-sm-2"
              type="search"
              id="Search"
              placeholder="Search"
              aria-label="Search"
              name="Search"
            />
            <button class="btn btn-outline-info my-2 my-sm-0" type="submit">
              Search
            </button>
          </form>
          <li class="nav-item" style="margin-left: 5rem">
            <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
          </li>
          {% if not current_user.isManager and not current_user.isAdmin %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('ticket.request_manager')}}"
              >Request
            </a>
          </li>
          {% endif %}
          <li class="nav-item">{% block displayUserName %} {% endblock %}</li>
        </ul>
      </div>
    </div>
    {% endif %}
  </nav>
  <body
    background="{{ url_for('static', filename='mainBG.jpeg') }}"
    style="height: 100%; background-repeat: no-repeat; background-size: cover"
  >
    <div style="margin: 2rem 10rem 0 10rem">
      {% block content %}{% endblock %}
    </div>
  </body>
  <script
    src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"
  ></script>
</html>

app/templates/cart.html
{% from 'productMacro.html' import productCartView %} {% extends "base.html" %}
{% block displayUserName %}
<a class="nav-link" style="color: rgb(86, 86, 86)"
  >Welcome {{current_user.username}}</a
>
{% endblock %} {% block content %} {% if message %}
<div class="alert alert-warning" role="alert">{{message}}</div>
{% endif %}
<ul class="list-group">
  <li
    class="list-group-item"
    style="
      height: 4rem;
      display: flex;
      flex-direction: row;
      justify-content: space-evenly;
    "
  >
    <h6>Product</h6>
    <h6>Value</h6>
    <h6>Quantity</h6>
    <h6>Value for the item</h6>
  </li>

  {% if cartDataProp.keys()|length == 0 %}
  <div class="alert alert-warning" role="alert" style="margin-top: 2.5rem">
    Nothing in the cart.
  </div>
  {% else %} {% for product in cartDataProp %} {% if cartDataProp[product]>0%}
  {{productCartView(product,cartDataProp[product])}} {% endif %} {% endfor %}
  {% if discount %}
  <li class="list-group-item disabled" style="
  margin-top: 0.5rem;
  height: 3rem;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  "
  >
    <h6>{{discountMessage}}</h6>
    <h6 style="margin-right: 4rem;">- {{discount}} Rs</h6>
  </li>
    {% endif %} 
  <li
    class="list-group-item"
    style="
      margin-top: 0.5rem;
      height: 3rem;
      display: flex;
      flex-direction: row;
      justify-content: space-between;
    "
  >
    <h6>Total</h6>
    <h6 style="margin-right: 4.25rem">{{totalValue-discount}} Rs.</h6>
  </li>

  {% endif %}
</ul>
  {% if cartDataProp.keys()|length != 0 %}
  <form method="POST" action="{{url_for('cart.handleBuyNow')}}">
    <div class="form-group"></div>
    <input type="submit" name="Buy Now" value="Buy Now" class="form-control btn btn-dark" />
  </form>

  {% endif %} {% endblock %}
</li>

app/templates/macros.html
{% macro regLoginForm(form) %}

<form
  method="POST"
  action="{{form.action}}"
  class="form"

>
  {{ form.csrf_token }} {{form.hidden_tag()}}
  <div>{{form.username(class='form-control')}}</div>
  <div>{{form.password(class="form-control")}}</div>
  <div style="margin: 1rem;">
    <input type="radio" name="isAdmin" id="isAdmin" value="Yes"> Admin Login? </input>
    <input type="radio" name="isManager" id="isManager" value="Yes"> Manager Login? </input>
  </div>
  <div>{{form.submit(class='form-control btn-info')}}</div>
</form>
{% if form.errors%} {{form.errors}} {% endif %} {% endmacro %}


{% macro ticketForm(form) %}
<h6 style="color: rgb(86, 86, 86)">Raise a ticket</h6>
<form
  method="POST"
  action="{{url_for('ticket.raise_ticket')}}"
  class="form-inline"
  

>
<div class="form-group">
  {{ form.csrf_token }} 
  <div>
    {{form.ticketRequest(class="form-control")}}  
    {{form.ticketTarget(class="form-control")}}
    {{form.ticketDetails(class="form-control")}}
    {{form.submit(class=" form-control btn-info")}}
  </div>
</div>
</form>
{% endmacro %}

{% macro adminTicketView(ticket) %}
<style>
  h6{
    color:rgb(86, 86, 86)
  }

</style>
<div style="
    display: flex;
    width: 100%;
    flex-direction: row;
    justify-content: space-between;
  ">
    <h6>{{ticket.ticketRequest}}</h6>
    <h6>{{ticket.ticketTarget}}</h6>
    <h6>{{ticket.ticketDetails}}</h6>
    <h6>{{ticket.raisedBy}}</h6>
    <form
    method="POST"
    action="{{url_for('ticket.handle_ticket',kwargs = {'ticketId' : ticket.ticketId,'approved':True})}}"
  >
  <input class = "btn btn-info" type="submit" name="Accept" value="Accept" id="response" />
</form>
<form
    method="POST"
    action="{{url_for('ticket.handle_ticket',kwargs = {'ticketId' : ticket.ticketId,'approved':False})}}"
  >
<input class = "btn btn-info"type="submit" name="Deny" value="Deny" id="response" />
</form>
</div>
{% endmacro %}


{% macro sectionCard(section) %}
<div style="margin: 0.25rem 0.25rem;">
    <a 
    href='{{url_for("section.section_view",sectionCategory = section.sectionKey)}}' class="btn btn-light">{{section.sectionKey|capitalize}}</a>
</div>
{% endmacro %}

app/templates/productMacro.html
{% macro cartControlUtil(quantityInCart,productId,origin="")%} {% if origin ==
"cart"%}
<div
  style="
    height: 2rem;
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    margin-top: 0.25rem;
    width: 8rem;
  "
>
  {% else %}
  <div
    style="
      height: 2rem;
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      margin-top: 0.25rem;
    "
  >
    {% endif %}
    <form
      method="post"
      action="{{url_for('cart.edit_cart',kwargs ={'productId':productId,'action':'remove','origin':origin})}}"
      type="button"
      class="btn btn-secondary"
    >
      <input type="submit" value="<" name="<" style="all: unset" />
    </form>
    <h6>{{quantityInCart}}</h6>
    <form
      method="post"
      action="{{url_for('cart.edit_cart',kwargs ={'productId':productId,'origin':origin})}}"
      type="button"
      class="btn btn-secondary"
    >
      <input type="submit" value=">" name=">" style="all: unset" />
    </form>
  </div>
  <div>
    <form
      method="post"
      action="{{url_for('cart.edit_cart',kwargs ={'productId':productId,'action':'clean','origin':origin})}}"
      type="button"
      class="btn btn-secondary"
      style="margin-top: 0.25rem; width: 100%"
    >
      <input
        type="submit"
        value="Remove all"
        name="Remove all"
        style="all: unset"
      />
    </form>
  </div>

  {% endmacro %} {% macro productForm(form,sections) %}
  <div  style="width: 60%;">
  <h6 style="color: rgb(86, 86, 86)">Add a new product</h6>
    <form class="form "method="POST" action="{{form.action}}">
      {{ form.csrf_token }} {{form.hidden_tag()}} 
      <div class="form-group">

        {{form.productName(class="form-control")}}
        {{form.productImage(class="form-control")}}
        <div class="form-group">

          <label >Expiry Date</label>
          {{form.expiryDate(class="form-control")}}
        </div>
        <div class="form-group">

          <label > Manufacturing Date</label>
          {{form.manufacturingDate(class="form-control")}}
        </div>
      </div>
<div class="form-group">

  {{form.valuePerUnit(class="form-control")}}
  {{form.quantityInStore(class="form-control")}}
  
  
  <select class="form-control" name="section" id="section">
    {% for sec in sections %}
    <option value="{{ sec }}" selected>{{ sec }}</option>
    {% endfor %}
  </select>
  {{form.submit(class="form-control btn-info")}}
</div>
</form>
</div>
{% endmacro %} {% macro productCard(productData) %}
  <div>
    {% if productData.quantityInStore == 0 %}
    <div
      class="card"
      style="
        height: 350px;
        width: 12rem;
        background-color: #64cddd71 !important;
        margin-left: 0.25rem;
        position: absolute;
        z-index: 1;
        align-items: center;
      "
    >
      <h5 style="margin-top: 9rem; background: white; width: 100%">
        Out of Stock
      </h5>
    </div>
    {% endif %}
    <div
      class="card"
      style="
        height: 350px;
        width: 12rem;
        background-color: #64cddd !important;
        margin: 0.25rem 0.25rem;
      "
    >
      <div
        class="card-body"
        styles="display:flex !important; flex-direction:row;"
      >
        <h5 class="card-title" styles="font-size:1vw">
          {{productData.productName}}
        </h5>
        <h6 styles="font-size:0.75vw">{{productData.valuePerUnit}} Rs</h6>
      </div>
      <img
        class="card-img-top"
        src="{{productData.productImage}}"
        alt="Card image cap"
        style="height: 10rem"
      />
      <a
        href="{{url_for('product.product_detail_view',productId=productData.productId)}}"
        style="position: absolute; right: 1rem; top: 0.5rem; color: white"
      >
        <span class="material-symbols-outlined"> info </span>
      </a>
      {% if productData.quantityInCart %}
      {{cartControlUtil(productData.quantityInCart,productData.productId)}} {%
      else %}
      <form
        method="post"
        action="{{url_for('cart.edit_cart',kwargs ={'productId':productData.productId})}}"
        type="button"
        class="btn btn-secondary"
      >
        <input
          type="submit"
          value="Add to cart"
          name="Add to cart"
          style="all: unset"
        />
      </form>
      {% endif %}
    </div>
  </div>
  {% endmacro %} {% macro productCartView(productData,quantity) %}
  <li
    class="list-group-item"
    style="
      height: 4rem;
      display: flex;
      flex-direction: row;
      justify-content: space-evenly;
      margin-top: 0.5rem;
      align-items: center;
    "
  >
    <img
      style="max-width: 100%; max-height: 100%"
      src="{{productData.productImage}}"
    />
    <div>
      <h5>{{productData.productName}}</h5>
    </div>
    <h6>{{productData.valuePerUnit}} Rs</h6>
    <h6>{{quantity}}</h6>
    {{cartControlUtil(productData.quantityInCart,productData.productId,'cart')}}
    <h6>{{quantity*productData.valuePerUnit}} Rs</h6>
  </li>
  {% endmacro %} {% macro productDetailView(productData) %}
  <style>
    h5 {
      color: rgb(86, 86, 86);
    }
    h6 {
      color: rgb(86, 86, 86);
    }
  </style>
  <div
    style="
      height: 30rem;
      display: flex;
      padding: 0rem 2rem 0rem 2rem;
      flex-direction: row;
    "
  >
    <img
      style="max-width: 100%; max-height: 100%; margin-right: 10rem"
      src="{{productData.productImage}}"
    />
    <div style="align-self: center">
      <h5>{{productData.productName}}</h5>
      <h6>{{productData.valuePerUnit}} Rs per unit</h6>
      <h6>Section : {{productData.section}}</h6>
      <h6>
        Total for this item :
        {{productData.quantityInCart*productData.valuePerUnit}} Rs
      </h6>
      {% if productData.quantityInCart %}
      {{cartControlUtil(productData.quantityInCart,productData.productId,origin
      = 'detailView')}} {% else %}
      <form
        method="post"
        action="{{url_for('cart.edit_cart',kwargs ={'productId':productData.productId,'origin':'detailView'})}}"
        type="button"
        class="btn btn-secondary"
      >
        <input
          type="submit"
          value="Add to cart"
          name="Add to cart"
          style="all: unset"
        />
      </form>
      {% endif %}
    </div>
  </div>
  {% endmacro %}
</div>
{% macro editProductForm(form,productsList) %}
<div style="width: 30%;">

  <h6 style="color: rgb(86, 86, 86)">Edit product</h6>
  <form
  method="POST"
  action="{{url_for('product.edit_product')}}"
  style="
    display: flex;
    width: 100%;
    flex-direction: column;
    justify-content: space-between;
    "
>
<div class = "form-group inline"style="display: flex; flex-direction: row">
  <select class='form-control'name="productToEdit" id="productToEdit">
    {% for product in productsList %}
    <option value="{{ product.productName }}" selected>
      {{ product.productName }}
    </option>
    {% endfor %}
  </select>
  {{form.productValue}}
</div >
  <div>
    Change Stock
    <input
    type="checkbox"
    id="changeStock"
    name="changeStock"
    value="changeStock"
    />
  </div>
    <select class="form-control" name="productInStock" id="productInStock">
      {% for stockValue in ['Change stock','Out of stock'] %}
      <option value="{{ stockValue }}" selected>{{ stockValue}}</option>
      {% endfor %}
    </select>
    {{form.unitsInStock(class="form-control")}} {{form.submitEdit(class="btn btn-info")}}

  </div>
</form>
{% endmacro %}